### ISSUE TITLE
OneHotEncoderEstimator --> OneHotEncoder in pyspark 3.0.1

### ISSUE THREAD

**Issue by caitsnyder** [learn-co-curriculum/dsc-machine-learning-with-spark#1]

**Comment by HudaKas** [comment]
OneHotEncoder which is deprecated in 2.3, is removed in 3.0 and OneHotEncoderEstimator is now renamed to OneHotEncoder. 

https://spark.apache.org/docs/3.0.0-preview/ml-migration-guide.html

**Comment by hoffm386** [comment]
Fixed in the latest version. Thank you for flagging!
